### PR TITLE
Implement the pref.discretization = 'values' / 'coeffs' syntax

### PR DESCRIPTION
**Pull request by Hadrien-Montanelli**
As suggested by @asgeirbirkis in #1550, this enables to select the discretizations via `pref.discretization = 'values'` or `pref.discretization = 'coeffs'`. Note that the defaults are still `chebcolloc2` for non-periodic problems and `trigcolloc` for periodic problems.

### CODE REVIEW

**Comment by Hadrien-Montanelli** [comment]
@asgeirbirkis, note that in order to test it, `determineDiscretization` is now public. Another change which might not be obvious is that `trigcolloc` is used for periodic problems even if `ultraS` is the default.

**Comment by asgeirbirkis** [comment]
@Hadrien-Montanelli the default discretization in `cheboppref` should now be `'values'`, not `@chebcolloc2`. Also, the values `values` and `coeffs` should be stored as strings, not as anonymous functions I think. Thirdly, I think we should be able to get rid of the `isPrefGiven` argument to `determineDiscretization`. Finally, the `discretization` part of the help text for `cheboppref` should be updated, advertising the `coeffs` and `values` options.

**Comment by Hadrien-Montanelli** [comment]
@asgeirbirkis, done.

**Comment by asgeirbirkis** [comment]
@Hadrien-Montanelli , I made some changes to ensure all chebtests passed (some of the linop ones were failing), and improvements so that linop methods could deal better with the new cheboppref syntax. Could you look at commits 585b8cc, 6cbc074 and 285bd24, and let me know if you're happy with the changes, in which case, I'll merge this pull request!

**Comment by Hadrien-Montanelli** [comment]
I am happy with the changes!

**Comment by asgeirbirkis** [comment]
Great, all merged! This requires some changes to chebgui which I've been working on, and hope to issue a pull request for tomorrow.

**Comment by Hadrien-Montanelli** [comment]
Thanks @asgeirbirkis

**Pull request merged**
