### PR TITLE
Feature poly transforms

### PR DESCRIPTION
**Pull request by ajt60gaibb**
This pull request contains: 

1) A new algorithm for `cheb2leg` and `leg2cheb`, 
2) Fast algorithms for `cheb2jac` and `cheb2jac` (currently only a direct approach is implemented in development), and 
3) A fast algorithm for `jac2jac` (currently only possible via `cheb2jac(jac2cheb(v,a,b),g,d)`, which is unstable).  

It based on a paper by myself, Marcus Webb (@marcusdavidwebb) and Sheehan Olver (@dlfivefifty): `Fast polynomials transforms based on Toeplitz and Hankel matrices`, see [pdf](http://math.mit.edu/~ajt/papers/fastconversion.pdf). The main step of the fast algorithm is a Toeplitz matrix multiply. 

1) `cheb2leg` and `leg2cheb`: 
The new algorithm is slightly (2 or 3 times) faster: 
```
% git branch development: 
v = randn(10000, 1); 
tic, w = leg2cheb( v ); toc 
tic, w = cheb2leg( v ); toc 
Elapsed time is 0.124428 seconds.
Elapsed time is 0.169971 seconds.
```
```
% git branch feature-poly-transforms: 
v = randn(10000, 1); 
tic, w = leg2cheb( v ); toc 
tic, w = cheb2leg( v ); toc 
Elapsed time is 0.053217 seconds.
Elapsed time is 0.079181 seconds.
```
and
```
% git branch development: 
v = randn(100000, 1); 
tic, w = leg2cheb( v ); toc 
tic, w = cheb2leg( v ); toc 
Elapsed time is 1.123032 seconds.
Elapsed time is 2.782115 seconds.
```
```
% git branch feature-poly-transforms: 
v = randn(100000, 1); 
tic, w = leg2cheb( v ); toc 
tic, w = cheb2leg( v ); toc 
Elapsed time is 0.413516 seconds.
Elapsed time is 1.074678 seconds.
```

2) `cheb2jac` and `cheb2jac`: 
The implementation is currently based on the direct approach.  In this pull request, the algorithm uses the direct approach for `N<=512` and a fast algorithm otherwise.
```
v = randn(100000, 1); 
tic, w = jac2cheb( v, .1, .4 ); toc 
tic, w = cheb2jac( v, pi/3, sqrt(2)/2 ); toc 
Elapsed time is 4.057954 seconds.
Elapsed time is 2.779676 seconds.
```
(I have not done a comparison with Mikael's `jac2cheb` and `cheb2jac` algorithm here because his algorithm is not implemented in Chebfun.)

3) `jac2jac`: 
This is a fast algorithm for converting between different Jacobi expansions and is a new proposed command.
```
v = randn(100000, 1); 
tic, w = jac2jac( v, pi/3, sqrt(2)/2, 1.1, -.2 ); toc
Elapsed time is 3.951507 seconds.
```

While testing it was impressive how many commands are using Legendre technology. I hope this pull request continues that trend.

### CODE REVIEW

**Comment by MikaelSlevinsky** [comment]
1) The new algorithm for `cheb2leg` and `leg2cheb` is slightly faster, 👍, but as I mentioned offline, the accuracies are likely to be asymptotically equal and results depend on how the coefficients are qualified, e.g. asymptotically bounded is different from i.i.d. normal.

2) In case anyone is interested, here are the timing results for my `jac2cheb` and `cheb2jac` methods:
```julia
julia> using FastTransforms

julia> c = randn(100_000);

julia> @time cjt(c,.1,.4);
  2.683202 seconds (284 allocations: 16.036 MB, 0.47% gc time)

julia> @time icjt(c,π/3,√2/2);
  6.109333 seconds (263 allocations: 36.634 MB, 0.09% gc time)
```

3) Bravo.

**Comment by nickhale** [comment]
This is very impressive.

I've made a few changes (which might eke out a little more speed in the small N cases), but otherwise I'm happy with the code. 

I'll try and read the paper more carefully over the long weekend. If I have no further suggestions then I'll merge on Tuesday.

**Comment by ajt60gaibb** [comment]
Thanks, Nick.   

@nickhale cannot make my code run faster: #LifeAmbitousRealised.

**Comment by nickhale** [comment]
> which might eke out a little more speed in the small N cases

@ajt60gaibb, see above. Try harder next time.

**Comment by ajt60gaibb** [comment]
FYI: @dlfivefifty, @marcusdavidwebb

**Pull request merged**
