### PR TITLE
Do not use SPTOEPLITZ command, and fix a bug for even case.

### PR DESCRIPTION
**Pull request by Hadrien-Montanelli**

### CODE REVIEW

**Comment by Hadrien-Montanelli** [comment]
(Closes #1826.)

**Comment by ajt60gaibb** [comment]
This limits the size of discretizations to less than `4000` and can turn an `O(n)` ODE solver into an `O(n^2)` solver.

**Comment by Hadrien-Montanelli** [comment]
Thanks @ajt60gaibb for your comment. I've just pushed a new change. (Closes #1912.)

**Comment by ajt60gaibb** [comment]
The new change has not appeared.

**Comment by Hadrien-Montanelli** [comment]
I know -- I don't exactly know what's going on, I'm creating a new branch instead.

**Comment by Hadrien-Montanelli** [comment]
@ajt60gaibb I've issued a new pull request.

**Pull request closed without merging**
