### PR TITLE
Add coeffs2vals disk sphere

### PR DESCRIPTION
**Pull request by heatherw3521**
This addresses issue #2322 .  It adds `coeffs2vals` and `vals2coeffs` for spherefun and diskfun objects, and also adds these and related functions for spherefunv, diskfunv and chebfun2v objects.

### CODE REVIEW

**Comment by MikaelSlevinsky** [comment]
Somehow I didn't get a notification for this PR even though it linked to the issue. I haven't tried it out, but thank you for looking into this!

**Comment by heatherw3521** [comment]
Happy to do it! Let me know if you want some additional changes.

**Comment by ajt60gaibb** [comment]
Sorry, that I took so long on this.  I didn't realize that I was assigned to review this or forgot that this PR existed.  That's completely my fault.   

Anyway, it's a nice clean PR. I am just running all the tests now. A few of the tests crash, @heatherw3521, would you care to take a look? 

```
The following tests failed or crashed:
   chebfun2/test_contour3.m
   diskfun/test_contour3.m
   diskfunv/test_coeffs_vals.m
   spherefun/test_contour3.m
```

**Comment by heatherw3521** [comment]
@ajt60gaibb The diskfunv test now works. The other tests (contour3 tests) passed without trouble for me. I'm not sure why they crashed for you.

**Comment by ajt60gaibb** [comment]
Ah, I ran it on a remote server without a proxy X11 server.  That's my fault.

**Pull request merged**
