### PR TITLE
Add aaatrig

### PR DESCRIPTION
**Pull request by baddoo**
Adds files for periodic extension of AAA.

### CODE REVIEW

**Comment by nakatsukasayuji** [comment]
Thanks Peter, 
- The example should be removed from the branch, this should be published later separately (email LNT the pdf first). 
- Please prepare a test code test_aaatrig in the folder tests/chebfun. These should be 'easy' tests that don't depend on e.g. hardware or MATLAB version. 
- In your complex example 
Z = exp(1i*linspace(-pi,pi,1e3)');
f = @(t) exp(1i*tan(t/2));
F = f(Z);
[rtrig, pol, res, zer, zj, fj, wj, errtrig] = aaatrig(F,Z);

 disp([f(pol) f(zer)]) gives me
 -1.4865e+02 + 6.5504e+01i  -6.3361e-03 + 2.7888e-03i
   9.9611e+02 - 1.5740e+03i   3.2333e-04 - 5.0999e-04i
  -9.7057e+02 + 5.1018e+03i  -4.0708e-05 + 2.1280e-04i
  -7.2845e+02 - 5.1432e+03i  -6.1971e-03 - 3.0970e-03i
   9.2076e+02 + 1.6205e+03i  -3.0168e-05 - 2.1459e-04i
  -1.4546e+02 - 7.2611e+01i   2.9804e-04 + 5.2554e-04i

Is this a bug?

**Comment by baddoo** [comment]
Thanks for looking at this, Yuij. I'll prepare a test code.

Regarding the example, I think that it's OK since f = exp(1i*tan(z/2)) doesn't have any poles or zeros in the complex plane, but its rational approximant will. The analogous case for AAA (not trig) is

Z = exp(1i*linspace(-pi,pi,1e3)');
f = @(t) exp(1i*t);
F = f(Z);
[r, pol, res, zer] = aaa(F,Z);

and disp([f(pol) f(zer)]) gives me

  -4.8789e+01 - 2.2414e+02i  -1.0612e-03 - 4.8407e-03i
  -2.1399e+01 + 2.2784e+02i  -4.5783e-04 + 4.9226e-03i
   2.8154e+03 + 2.3314e+03i   2.3989e-04 + 1.9754e-04i
  -1.3913e+04 - 3.9666e+03i  -7.5488e-05 - 2.1251e-05i
   2.5122e+03 - 2.6454e+03i   2.1317e-04 - 2.2529e-04i
   2.2121e+04 - 1.3134e+03i   5.1038e-05 - 3.1953e-06i
  -1.3330e+04 + 5.5823e+03i  -7.2179e-05 + 3.0452e-05i

which is similar to the result given by AAAtrig.

**Comment by nakatsukasayuji** [comment]
Ok thanks, I see. Let me know once the test codes are pushed.

**Comment by baddoo** [comment]
Thanks, the test codes are now pushed to the feature-aaatrig branch.

**Pull request closed without merging**
