### PR TITLE
Feature spherefun plotting

### LINKED ISSUE #2007: Spherefun: plot equator and Greenwich meridian by default
John Boyd (jpboyd@umich.edu) has been visiting Oxford and has made a suggestion about Spherefun based on decades of experience with computing on the sphere.  Many people active in this area have the habit of including a circle for the equator and another circle for the Greenwich meridian in every plot.  He suggests, and I agree with him, that Spherefun should do the same.  Of course this could be a feature on by default but turn-offable.  What do you think, @gradywright and @heatherw3521 and @ajt60gaibb?

### PR DESCRIPTION
**Pull request by gradywright**
Adds new capabilities to the `spherefun/surf' command, including plotting using different map projections and adding grid lines to plots.  Try for example:
```
f = cheb.gallerysphere('vortices');
surf(f,'projection','hammer','grid','k-')
```

Also changes some of the `cheb.gallerysphere` examples to use these new plotting capabilities.

Closes #2007, also adds a fix for #2120.

### CODE REVIEW

**Comment by ajt60gaibb** [comment]
Seems very useful for visualizations.

**Comment by Hadrien-Montanelli** [comment]
@trefethen @gradywright @ajt60gaibb I'm happy to merge this - it wasn't in the v5.7 milestone though. Thoughts?

**Comment by ajt60gaibb** [comment]
I hope it can be merged before the release.  I'm not sure what the policy is on milestones.

**Comment by gradywright** [comment]
I would very happy to have this merged before the release.  I can come up with a brief statement regarding the new capabilities if necessary.

**Comment by trefethen** [comment]
Fine with me.

**Comment by Hadrien-Montanelli** [comment]
Cool - I'll run the tests and press the button!

**Comment by trefethen** [comment]
@sfilip and I have decided to go ahead with today's v5.7.0 release as scheduled without merging this pull request.  The reason is that our quick test showed that it doesn't have functionality a user might expect.  In particular, one should be able to type `surf(f,'grid')` without being forced to type e.g. `surf(f,'grid','k')`.  Also it is puzzling what the relationship is of `plot` and `surf`.  The help text of `plot` says it calls surf, but it does not mention features such as `grid` and the experiment `plot(f,'grid','k')` fails.

**Comment by Hadrien-Montanelli** [comment]
@gradywright - any update on this? Happy to help.

**Comment by gradywright** [comment]
I could definitely use the help @Hadrien-Montanelli.  It would be great if you could take a crack at addressing the issues @trefethen and @sfilip raised.

**Comment by Hadrien-Montanelli** [comment]
Ok - I'll take a look tomorrow. 

Hadrien

**Comment by Hadrien-Montanelli** [comment]
I see two different issues.

1. One should be able to type surf(f,'grid') without being forced to type e.g. surf(f,'grid','k'). The commit above fixed this.

2. What is the relationship between plot and surf? @gradywright - thoughts?

**Comment by gradywright** [comment]
I don't know what the relationship should be.  In the development branch, the main difference is that `plot(f,'-.')` will plot the pivots and row/column slices, whereas `surf(f,'-.')` is not supported.  The same is true for `chebfun2` and `diskfun`.

**Comment by Hadrien-Montanelli** [comment]
To summarise: 

`plot(f)` does the standard plotting. In practice, it calls directly `surf(f)` on line 202 of `spherefun/plot`;

`plot(f, '-.')` also plots the pivots and row/column slices;

`plot(f, 'grid')` is not supported;

`surf(f)` is equivalent to `plot(f)`;

`surf(f, '-.')` is not supported;

`surf(f, 'grid')` also plots the grid.

Am I right? @trefethen - thoughts?

**Comment by trefethen** [comment]
@Hadrien-Montanelli and I have just changed the help texts in spherefun plot and surf so that each points to the other's additional capabilities.  These are great new features and after running the tests, @Hadrien-Montanelli plans to merge.

**Comment by gradywright** [comment]
Thanks @Hadrien-Montanelli and @trefethen!

**Pull request merged**
