### PR TITLE
fix-trigtech-diffmat

### PR DESCRIPTION
**Pull request by nickhale**
Remove duplicated `trigtech.diffmat()` and `trigcolloc.diffmat()` codes.

Move `trigcolloc.diffmat()` to `@trigcolloc/diffmat.m`

Scale `trigcolloc.diffmat()` to [-1,1) rather than [-pi,pi).

Fix bug for higher-order derivatives in `trigcolloc.diffmat()`.

Modify tests accordingly.

### CODE REVIEW

**Comment by trefethen** [comment]
Nick, I'm delighted at the many many Chebfun
improvements you're making lately.

And as you can imagine, I am, as always, curious
about what you're up to in research these days.  Are
you doing work in which Chebfun is playing a role,
and is that motivativing some of these developments?
Or is Chebfun more or less
a hobby separate from your research?

Either way, thanks.

    Nick

On 15/05/15 10:43, Nick Hale wrote:
> Remove duplicated `trigtech.diffmat()` and `trigcolloc.diffmat()` codes.
>
> Move `trigcolloc.diffmat()` to `@trigcolloc/diffmat.m`
>
> Scale `trigcolloc.diffmat()` to [-1,1) rather than [-pi,pi).
>
> Fix bug for higher-order derivatives in `trigcolloc.diffmat()`.
>
> Modify tests accordingly.
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/chebfun/chebfun/pull/1498
>
> -- Commit Summary --
>
>   * Remove duplicated trigtech.diffmat and trigcolloc.diffmat codes.
>
> -- File Changes --
>
>     A @trigcolloc/cumsummat.m (13)
>     M @trigcolloc/diff.m (4)
>     A @trigcolloc/diffmat.m (115)
>     M @trigcolloc/trigcolloc.m (127)
>     M diffmat.m (3)
>     M tests/trigtech/test_diffmat.m (21)
>
> -- Patch Links --
>
> https://github.com/chebfun/chebfun/pull/1498.patch
> https://github.com/chebfun/chebfun/pull/1498.diff
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/chebfun/chebfun/pull/1498
>

-- 
L. N. Trefethen FRS
Professor of Numerical Analysis and Fellow of Balliol College, Oxford University
Global Distinguished Professor, New York University
Postal address: Oxford Maths Inst, Woodstock Rd, Oxford OX2 6GG, UK
people.maths.ox.ac.uk/trefethen, (+44) 1865 615317

**Comment by Hadrien-Montanelli** [comment]
@nickhale, misc/diffmat is failing because of line 117 of diffmat -- I think we shouldn't rescale it here.

**Comment by nickhale** [comment]
You're right. It should be fixed now.

**Comment by Hadrien-Montanelli** [comment]
Great! Thanks for making the code clearer!

**Pull request merged**
