### PR TITLE
Implement mixed technology in chebfun2

### PR DESCRIPTION
**Pull request by danfortunato**
This pull request implements mixed technology in `chebfun2`, i.e., technology that is different in the x- and y-directions. The `chebfun2` constructor has been modified to allow for variations on the arguments `'trig'` / `'periodic'`, `'equi'`, `'coeffs'`, and preferences, in order to specify which dimension the argument refers to. For example, the flag `'trig'` by itself specifies a periodic discretization in both x and y; the new syntax `{'trig', []}` specifies a periodic discretization in x only. The value of the "empty" argument does not matter; the syntax `{'trig', ''}` achieves the same behavior.

### `'trig'` in one dimension
Construct a `chebfun2` that is periodic in one dimension. For example:
```
u = chebfun2(@(x,y) ..., {'trig', []});
u = chebfun2(vals_cheb_trig, {[], 'periodic'});
```
Displaying the `chebfun2` shows this information. The first function displays as `chebfun2 object  (trig in x)` while the second displays as `chebfun2 object  (trig in y)`.

### `'equi'` in one dimension
Construct a `chebfun2` from values on a tensor-product grid that is equally spaced in one dimension. For example:
```
u = chebfun2(vals_equi_cheb, {'equi', []});
u = chebfun2(vals_cheb_equi, {[], 'equi'});
```

### `'coeffs'` in one dimension
Construct a `chebfun2` from a bivariate discretization of coefficients in one dimension and values in another. For example:
```
u = chebfun2(coeffs_vals, {'coeffs', []});
u = chebfun2(vals_coeffs, {[], 'coeffs'});
```

### `'trig'` and `'coeffs'` in one dimension
These operations are composable. For example:
```
chebfun2(trigcoeffs_chebvals, {'coeffs', []}, {'trig', ''});
chebfun2(trigcoeffs_chebcoeffs, 'coeffs', {'trig', []});
chebfun2(trigvals_chebcoeffs, {'', 'coeffs'}, {'trig', ''});
chebfun2(trigcoeffs_trigvals, 'trig', {'coeffs', ''});
chebfun2(chebvals_trigcoeffs, {[], 'trig'}, {[], 'coeffs'});
```

### Preferences in one dimension
Preferences can also be specified for each dimension. For example:
```
pref = chebfunpref();
pref.tech = @trigtech;
f = chebfun2(@(x,y) sin(2*pi*x).*y, {pref, []});
```

### CODE REVIEW

**Comment by trefethen** [comment]
@danfortunato and @ajt60gaibb, this functionality looks marvelous.  As usual, I am concerned about the simplicity and obviousness of the user experience, and I would like us to agree on the simplest syntax before anything is merged.  Rather than `chebfun2(...,{'trig',[]}` and `chebfun2(...,{[],'trig'})`, how about `chebfun2(...,'trigx')` and `chebfun2(...,'trigy')`?  I have no objection to more complicated syntaxes being available for specification of complicated options, but the basic use of Chebfun is always simply to compute with functions, and for that, `{'trig',[]}` seems awfully complicated.  What are your thoughts?

It will be great to have this in Chebfun!

**Comment by danfortunato** [comment]
I am happy with `'trigx'` and `'trigy'`. I agree, the current syntax is not the cleanest! Should the `'coeffs'` and `'equi'` options similarly change to `'coeffsx'` / `'coeffsy'` and `'equix'` / `'equiy'`? The only one that would remain in the current form would then be preferences.

**Comment by danfortunato** [comment]
The syntax is now:

### `'trig'` in one dimension
```
u = chebfun2(@(x,y) ..., 'trigx');
u = chebfun2(vals_cheb_trig, 'periodicy');
```

### `'equi'` in one dimension
```
u = chebfun2(vals_equi_cheb, 'equix');
u = chebfun2(vals_cheb_equi, 'equiy');
```

### `'coeffs'` in one dimension
```
u = chebfun2(coeffs_vals, 'coeffsx');
u = chebfun2(vals_coeffs, 'coeffsy');
```

### `'trig'` and `'coeffs'` in one dimension
```
chebfun2(trigcoeffs_chebvals, 'coeffsx', 'trigx');
chebfun2(trigcoeffs_chebcoeffs, 'coeffs', 'trigx');
chebfun2(trigvals_chebcoeffs, 'coeffsy', 'trigx');
chebfun2(trigcoeffs_trigvals, 'trig', 'coeffsx');
chebfun2(chebvals_trigcoeffs, 'trigy', 'coeffsy');
```

**Comment by ajt60gaibb** [comment]
@danfortunato, it's very nice that this was not a major change!  Can you add some documentation to the help text of `chebfun2` so that this new feature is advertised.

**Comment by ajt60gaibb** [comment]
Also, how does one go about extracting the Fourier-Chebyshev coefficients?  For example, 
```
f = chebfun2(@(x,y) sin(pi*x), 'trigx');
chebcoeffs2(f, 10, 10)
Error using chebfun2/chebcoeffs2
Too many input arguments. 
coeffs2(f, 10, 10)
Error using trigtech/chebcoeffs (line
20)
F does not have a finite Chebyshev
series. Please input N.
Error in classicfun/chebcoeffs (line
11)
out = chebcoeffs(f.onefun,
varargin{:});
Error in chebfun/chebcoeffs (line 93)
    out = chebcoeffs(f.funs{1}, N,
    kind);
Error in chebfun2/chebcoeffs2 (line 29)
rows_coeffs = chebcoeffs(rows);
Error in chebfun2/coeffs2 (line 47)
[cols_coeffs, d, rows_coeffs] =
chebcoeffs2( f ); 
```

**Comment by NBoulle** [comment]
`chebfun2/poisson` might need to be fixed as well and I'm not sure if this will work with `chebop2` or `spin2`.

**Comment by danfortunato** [comment]
@ajt60gaibb, this is a good point. One solution is to add a `coltech` and `rowtech` to `separableApprox` (defaulting them to `chebtech2`), and then use the transforms given by those technologies. (Also, note that `chebcoeffs2` only takes one argument.)

This same bug actually exists in `spherefun` and `diskfun` too:

```
>> f = randnfunsphere;
>> chebcoeffs2(f)

Error using trigtech/chebcoeffs (line 20)
F does not have a finite Chebyshev series. Please input N.

Error in classicfun/chebcoeffs (line 11)
out = chebcoeffs(f.onefun, varargin{:});

Error in chebfun/chebcoeffs (line 93)
    out = chebcoeffs(f.funs{1}, N, kind);

Error in separableApprox/chebcoeffs2 (line 28)
cols_coeffs = chebcoeffs(cols);

Error in spherefun/chebcoeffs2 (line 17)
    [varargout{1:nargout}] = chebcoeffs2@separableApprox(varargin{:});
```

```
>> f = randnfundisk;
>> chebcoeffs2(f)
Error using trigtech/chebcoeffs (line 20)
F does not have a finite Chebyshev series. Please input N.

Error in classicfun/chebcoeffs (line 11)
out = chebcoeffs(f.onefun, varargin{:});

Error in chebfun/chebcoeffs (line 93)
    out = chebcoeffs(f.funs{1}, N, kind);

Error in separableApprox/chebcoeffs2 (line 29)
rows_coeffs = chebcoeffs(rows);

Error in diskfun/chebcoeffs2 (line 17)
[varargout{1:nargout}] = chebcoeffs2@separableApprox(varargin{:});
```

The naming is a bit awkward. `separableApprox` defines the function `chebcoeffs2` even though there is no requirement in `separableApprox` that Chebyshev technology be used. Why not make this function `coeffs2`? Then subclasses of `separableApprox` would not be required to implement `coeffs2`, as it would be based on the technology.

**Comment by danfortunato** [comment]
@NBoulle, you are right, although `chebfun2/poisson` and `chebop2` currently fail when the RHS is `'trig'` already:

```
>> f = chebfun2(@(x,y) sin(2*pi*x), 'trig');
>> N = chebop2(@(u) lap(u));
>> N.bc = 0;
>> u = N \ f;
Error using trigtech/chebcoeffs (line 20)
F does not have a finite Chebyshev series. Please input N.

Error in classicfun/chebcoeffs (line 11)
out = chebcoeffs(f.onefun, varargin{:});

Error in chebfun/chebcoeffs (line 93)
    out = chebcoeffs(f.funs{1}, N, kind);

Error in chebfun2/chebcoeffs2 (line 28)
cols_coeffs = chebcoeffs(cols);

Error in chebfun2/coeffs2 (line 47)
[cols_coeffs, d, rows_coeffs] = chebcoeffs2( f );

Error in chebfun2.poisson (line 138)
[Cf, Df, Rf] = coeffs2(f, m, n);

Error in chebop2.denseSolve (line 21)
    u = chebfun2.poisson(f+N.rhs, g, m, n);

Error in chebop2/solvepde (line 110)
    X = chebop2.denseSolve(N, f, m, n);

Error in  \  (line 20)
[varargout{1:nargout}] = solvepde(varargin{:});
```

**Comment by danfortunato** [comment]
These seem to be bugs with coefficients and `'trig'` in `separableApprox` that exist independent of this PR. @nickhale, do you think it is okay to merge this PR? Then we can fix the bugs in `separableApprox` that already exist.

**Comment by danfortunato** [comment]
I have made separate issues for these bugs:

- #2329 Chebfun2 loses 'trig' on various operations
- #2330 separableApprox/coeffs2 (and chebcoeffs2) assumes Chebyshev technology

**Comment by ajt60gaibb** [comment]
@nickhale, can I take a look and merge?

**Comment by nickhale** [comment]
I'm not sure why I'm being asked..

**Pull request merged**
