### PR TITLE
removed "(1 smooth surface)" from @chebfun2/disp.m

### PR DESCRIPTION
**Pull request by trefethen**
This does what it says on the tin: removes that pesky expression "1 smooth surface" from every display of a chebfun2.   (This is my first pull request!)

### CODE REVIEW

**Comment by ajt60gaibb** [comment]
OK. Should the analogous phrase be removed from `chebfun/disp`?  See, for example:

```
f = chebfun('x')
f =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]        2        -1        1 
vertical scale =   1 
```

**Comment by trefethen** [comment]
No, in the 1D case the "1 smooth piece" message has content: sometimes there are multiple pieces.
```
>> f = chebfun('abs(x)','splitting','on')
f =
   chebfun column (2 smooth pieces)
       interval       length     endpoint values  
[      -1, 1.2e-17]        2         1        0 
[ 1.2e-17,       1]        2         0        1 
vertical scale =   1    Total length = 4
```
So in 1D there is genuine information involved, whereas in 2D I believe there is no such information since *all* functions are smooth.  Please correct me if I'm overlooking something.

**Comment by ajt60gaibb** [comment]
OK.  After so many years of having `(1 smooth surface)` in the display, it looks empty without it.  But, I agree, it should be removed until there is a piecewise chebfun2.

**Comment by bhashemi** [comment]
A similar issue exists in ``spherefun`` which prints ``spherefun object (1 smooth surface) ``...

**Comment by gradywright** [comment]
Thanks @bhashemi.  I made the change on the `feature-spherefun-new` branch.

**Pull request merged**
