### PR TITLE
Feature chebfun3 new

### PR DESCRIPTION
**Pull request by bhashemi**
This is a pull-request regarding `chebfun3`, `chebfun3v` and `chebfun3t` classes. Codes in this branch are not fully ready to be merged, but probably 80% of the work is done. In particular some tests are to be added soon. So, it would be great if we could plan for a code-review to start. A good place to start the review process is probably the `chebfun3t` class since I don't intend to make major modifications here.

### CODE REVIEW

**Comment by ajt60gaibb** [comment]
Chebfun3 is much more efficient that I imagined possible. 3D is here!

**Comment by bhashemi** [comment]
@ajt60gaibb I am honored by your comment. Thank you.

**Comment by ajt60gaibb** [comment]
I have a problem that needs Chebfun3. I am running into quite a few bugs so I will put them here. You can make issues out of them if you wish. 

*chebfun3/roots*
A more descriptive error is helpful
```
roots(f)
Not enough input arguments.
Error in chebfun3/roots (line 14)
f = f./f.vscale; g = g./g.vscale; h = h./h.vscale;  
``` 
Can the help text be improved too?  ( I wanted to know if I could find zero lines of f and g. )
```
help chebfun3/roots
 roots    Poor man's method for finding common roots of three 3D functions:
    1) Find some initial guesses from the tensor of values of 
    obj_fun = f.^2+g.^2+h.^2.
    2) Apply 10 steps of Newton's method.
    3) Filter inaccurate results.
 
    See also chebfun3/root.
```
The help text for `min3` and `max3` needs work. 

*chebfun3/sum*
```
f = chebfun3(@(x,y,z) cos(x)+sin(y),[-2 3, -2 2 , -2 2]);
>> sum(f)
Error using  *  (line 52)
Matrix dimensions must agree.
Error in chebfun3/sum (line 40)
    ff = chebfun2(f.tubes*core'*f.rows');
```

*chebfun3/subsref*
```
f = chebfun3(@(x,y,z) cos(x)+sin(y),[-2 3, -2 2 , -2 2]);
>> f(1,:,:)
Error using  *  (line 52)
Matrix dimensions must agree.
Error in chebfun3/feval (line 33)
    out = chebfun2(f.tubes * core' * f.rows');
Error in chebfun3/subsref (line 19)
        out = feval(f, x, y, z);  
```

*chebfun3/constructor* 
This was strange: 
```
f = chebfun3(rand(1,10,1),[-2 3 -1 1 -1 1])
ans = 
    empty chebfun3
```
and this
```
f = chebfun3(rand(1,10,2))
Operands to the || and && operators must be convertible to logical scalar values.
Error in chebfun3/constructor>completeACA3D (line 1330)
while ( ( infNorm > tol ) && ( iter < width / factor) ...
Error in chebfun3/constructor>constructFromDouble (line 1195)
        pivotVals3D, ignore, ignore, ignore] = completeACA3D(op, ...
Error in chebfun3/constructor (line 51)
    f = constructFromDouble(op, dom, pref, isEqui);
Error in chebfun3 (line 79)
        f = constructor(f, varargin{:});
```

*chebfun3/hosvd* 
I am excited by `hosvd`.  It's great.  

Why are the modal singular values returned as row vectors, not column vectors? 
```
 f = chebfun3(@(x,y,z) cos(x.*y.*z),[-2 2 -2 2 -3 2]);
>> sv = hosvd(f)
sv = 
    [1x14 double]    [1x14 double]    [1x14 double]
```
To make sparse diagonal matrices out of them, one has to keep transposing. 

Thanks for Chebfun3.

**Comment by bhashemi** [comment]
Thank you so much @ajt60gaibb for lots of comments! I'll try to improve the code.

**Comment by mhsnjvd** [comment]
@bhashemi I am reviewing parts of the code and taking the liberty to push some small changes to the help text and other minor formatting things. I hope this is OK! Looks quite good 🎱 👍

**Comment by bhashemi** [comment]
Of course @mhsnjvd . Thanks for working on this.

**Comment by mhsnjvd** [comment]
@bhashemi In chebfun3/vscale.m in lines 22-27 you check for the two cases, ```trigtech``` or ```chebtech2``` but later in the function ```mypoints()``` you also check for ```chebtech1``` which is inconsistent. Actually I think we should just pass the tech of the input function to ```mypoints``` and check for the tech only there are return the appropriate points?

**Comment by mhsnjvd** [comment]
@bhashemi  in ```discrete_hosvd``` it's probably a good idea to add a reference?

**Comment by mhsnjvd** [comment]
@chebfun/team-guide ```fevalt``` should have a test, maybe merged with ```test_feval``` or maybe a
separate test of its own.

**Comment by mhsnjvd** [comment]
@bhashemi It would be better to add a couple more tests in ```test_hosvd``` to check all forms of output.

**Comment by mhsnjvd** [comment]
@bhashemi  In mtimes.m, the help text says: Pointwise multiplication for CHEBFUN3 objects

Is that true? I thought times.m does pointwise multiplication.

**Comment by mhsnjvd** [comment]
@bhashemi Please add tests for ```rdivide``` and ```mtimes```

**Comment by mhsnjvd** [comment]
@bhashemi  Please add tests for ```iszero``` and ```isreal```

**Comment by oliviersete** [comment]
@bhashemi Please add help text in `power`.

**Comment by oliviersete** [comment]
@bhashemi Maybe add a description line for `uminus`, e.g.
UMINUS(F) returns -F for a Chebfun3 object F.

**Comment by oliviersete** [comment]
@bhashemi Is `uplus` needed anywhere?

**Comment by oliviersete** [comment]
@bhashemi In `mrdivide`: Please add a check whether g=0.
Should there be a ckeck if f is empty?

**Comment by oliviersete** [comment]
@bhashemi `mldivide` calls `h = ldivide(f, g);` which calls `h = rdivide(g, f);`. Is there a reason for not directly calling the latter?

**Comment by oliviersete** [comment]
@bhashemi The following results in an error:
```
f = chebfun3(@(x,y,z) x);
power(f, eye(2))
```

**Comment by oliviersete** [comment]
Can the lines 32-34 in `scan` be removed? The option ct seems unused.

**Comment by oliviersete** [comment]
Maybe check in `scan` that input other than `'hold'` is the dimension dim=1, 2 or 3. For instance
```
f = chebfun3(@(x,y,z) x);
scan(f, 4)
```
gives a broken plot and `scan(f, [1; 2])` gives an error.

**Comment by bhashemi** [comment]
@mhsnjvd I think f598dff and 5cac1b0 should have addressed your review comments. Is that right?

**Comment by trefethen** [comment]
@bhashemi, would you please add a test for `chebfun3/gradient`.

**Comment by bhashemi** [comment]
@oliviersete thanks for your review comments. I tried to address most of them in 96d6e1f.

**Comment by bhashemi** [comment]
@jrus , `cumsum`, `cumsum2`, and `cumsum3` compute _indefinite_ integrals as opposed to `sum`, `sum2` and `sum3` which compute _definite_ integrals.

**Comment by oliviersete** [comment]
@bhashemi Maybe add in the help text of chebfun3/plot a description of the output, h = plot(f).
Maybe also add some comments to the code.

**Comment by oliviersete** [comment]
@bhashemi Should `chebfun3v/divergence` also work for 2-dimensional Chebfun3v objects?

**Comment by oliviersete** [comment]
@bhashemi Found a bug in `chebfun3v/laplacian`:
```
f = chebfun3(@(x,y,z) x); F = [f; f; f];
L = laplacian(F)
```
gives
```
L =
   chebfun3v object (Column vector) containing:
```
with no further output.

I think this is due to `L.nComponents = []`, which comes from creating an empty Chebfun3v in line 23.
Adding `L.nComponents = F.nComponents;` at the end fixes the display of the output, but might there be other things that are also not correctly assigned?

**Comment by oliviersete** [comment]
@bhashemi Should `chebfun3v/laplacian` also work for 2d Chebfun3v objects?

**Comment by oliviersete** [comment]
@bhashemi `chebfun3v/rdivide` is more powerful than `chebfun3v/ldivide`, as also division by a Chebfun3 object is allowed. The same holds for `mrdivide` and `mldivide`.
Maybe `ldivide(f,g)` could simply call `rdivide(g,f)`, and similarly `mldivide` could call `rldivide` ?

**Comment by oliviersete** [comment]
@bhashemi I think the `elseif` in lines 41-43 of `chebfun3v/power` could be removed, as the wrong input will be catched by the final `else`.

**Comment by oliviersete** [comment]
@bhashemi In `chebfun3v/quiver3` the handlich of an empty chebfun calls `quiver([])` which produces an error. Maybe handle that case differently?
Also maybe add the output argument in the help text.

**Comment by oliviersete** [comment]
@bhashemi Question related to `chebfun3v/vertcat`: I would expect that adding "nothing" (an empty Chebfun3) does not change the Chebfun3v, i.e., that `vertcat(f, []) = f` and `vertcat([], f) = f`.
Right now an empty Chebfun3v is returned in both cases. Should that be changed?

**Comment by oliviersete** [comment]
@bhashemi In `chebfun3v/mtimes`, should line 26 `F = mtimes(G.', F.');` be replaced by
`F = mtimes(G.', F.').';` ? This would fit the comment in l. 23 and be similar to l. 33.

**Comment by bhashemi** [comment]
@oliviersete thanks a lot for your very careful review of `chebfun3v`.

**Comment by mhsnjvd** [comment]
@bhashemi I have reviewed the code assigned to me and happy with it. The only thing I would request is a test for ```fold``` and ```unfold```.

**Comment by jaurentz** [comment]
At this point I believe `chebfun3` is 95% ready for release. There will always be bugs and room for improvement but I am optimistic that things are on the right track!

**Pull request merged**
