### PR TITLE
Feature simpler sampletest

### PR DESCRIPTION
**Pull request by jaurentz**
This pull request simplifies `sampleTest` for both `trigtechs` and `chebtechs`. See #1610.

### CODE REVIEW

**Comment by nickhale** [comment]
What's the rationale behind evaluating at `xeval = 1e-5*[-1;1];` in the `chebtech` case, rather than some pseudo-random value?

**Comment by asgeirbirkis** [comment]
Also, is there no way to unify the test for `chebtechs` and `trigtechs` and implement this method at the `smoothfun` level?

**Comment by aaustin141** [comment]
@asgeirbirkis:  Let's leave that consideration out for the moment.  We know that lots of the code in `chebtech` and `trigtech` is duplicated and can be factored out, but I think it's best not to push for that right now.

**Comment by jaurentz** [comment]
For `chebtech` I wanted 2 points that didn't show up on any of the grids and were in the least sampled part of the domain. I'm equally happy with pseudo random points though.

**Comment by trefethen** [comment]
Thanks @jaurentz.  I'd be very glad if this could be merged this week, assuming no difficulties turn up, since I'm working on a paper about constructors etc.

**Comment by nickhale** [comment]
I'd be in favour of pseudo random values. Might as well use the same ones as currently `trigTech`, i.e., 
```
% pseudo random sample points
xeval = [-0.357998918959666; 0.036785641195074];
```

Two other points:
 * I notice that the call `x = f.chebpts(n);` on line 19 is no longer required. As is the TODO at the start.
 * This change might remove the requirement for for `techprefs.sampleTestEps` (which I dislilked from the start). I see the desire to get this 'fixed' quickly, but I agree with @asgeirbirkis that it might be worthwhile unifying and solidifying `sampleTest` while it's in the L1 cache.

**Comment by aaustin141** [comment]
Can confirm:  this appears to get rid of the need for `sampleTestTol` (see #1560) on my machine.

**Comment by jaurentz** [comment]
I've update `chebtech/sampleTest` to use pseudo random values and have eliminated `sampleTestEps` from `chebtech` and `trigtech`.

**Comment by nickhale** [comment]
Once #1584 is merged this could do with some tidying up, but I'm happy with it for now.

The only problem is that test 31 of `chebfun/test_norm()` fails. The test expects a `min(f, -inf)` to occur at x = inf, but it's now returning a finite (but very large) number. I suspect this test is ill-conditioned anyway, but perhaps someone else should take a look.

**Comment by aaustin141** [comment]
@nickhale:  I've been seeing that test fail now for some time on my personal machine (but not on my workstation).  I think we fixed the issue somewhere in #1584, as it doesn't fail for me on that branch.

**Pull request merged**
