### PR TITLE
Adjoints for linear differential operators

### PR DESCRIPTION
**Pull request by jaurentz**
This pull request allows for the automatic computation of adjoints of linear differential operators. Integral and other exotic operators are not supported. This also only supports periodic or endpoint boundary conditions.

### CODE REVIEW

**Comment by jaurentz** [comment]
I think it would be best if #1788 was merged before this one.

**Comment by trefethen** [comment]
@jaurentz, I'm teaching the Exploring ODEs course at NYU and in today's lecture I would have enjoyed showing the students adjoints, but discovered this is still in a branch.  Can you give us a status update?  Is this something that should be mergeable into development?  What's your understanding of the state of this branch and its need for review?   - Thanks for any comments.

**Comment by jaurentz** [comment]
The last person I talked with about code review was @Hadrien-Montanelli who appears to still be assigned to the task. As far as I know that only issue is for someone to review it.

**Comment by Hadrien-Montanelli** [comment]
@jaurentz Since the method chebop/getBCType is only used in chebop/adjoint, maybe it should be moved at the bottom of the chebop/adjoint file?

**Comment by Hadrien-Montanelli** [comment]
@jaurentz Could you please add a couple of tests at the `chebop/adjoint` level?

**Comment by Hadrien-Montanelli** [comment]
All the tests pass - happy to merge it once there are more tests

**Comment by jaurentz** [comment]
Added a few more tests and hid some of the low level files inside the main adjoint routines.

**Comment by Hadrien-Montanelli** [comment]
@jaurentz brilliant - running the tests

**Pull request merged**
