### PR TITLE
Loosening the tolerance used for sampleTest for the construction of `smoothPart` of singfun. 

### PR DESCRIPTION
**Pull request by kuanxu**
To do so, a new field `sampleTestEps` is added to techPref@chebtech and techPref@trigtech. All tests passed.

### CODE REVIEW

**Comment by ajt60gaibb** [comment]
I was expecting you to just make a specialised `sampleTest` for `singfun`.  Does this simple change really need a new preference? 

(I will agree with whatever @aaustin141 thinks about it.)

**Comment by kuanxu** [comment]
@ajt60gaibb It seems to me that adding this new preference can make things easier. Otherwise, I need add a new input argument in each layer to pass down a specified tolerance from constructSmoothPart@singfun all the way down to sampleTest@chebtech. But I'm not very sure. I'll see what @aaustin141 say too.

**Comment by ajt60gaibb** [comment]
Oh, I see. @aaustin141 is omniscient.

**Comment by bhashemi** [comment]
All the tests pass on my machine.

**Comment by ajt60gaibb** [comment]
What did @aaustin141 think?

**Comment by kuanxu** [comment]
We just had the discussion in the weekly meeting and I think this fix made both @aaustin141 and @trefethen happy.

**Comment by ajt60gaibb** [comment]
OK. Great!

**Pull request merged**
