### PR TITLE
Feature rename spinprop

### PR DESCRIPTION
**Pull request by Hadrien-Montanelli**
This branch does the following (as agreed during the last Chebfun meeting):
1. Changes `S.linearPart` to  `S.lin`
2. Changes `S.nonlinearPart` to `S.nonlin`

Note: Has to be merged after #1982. Guide, examples and front page of the website have to be updated.

### CODE REVIEW

**Comment by Hadrien-Montanelli** [comment]
Any update @bhashemi?

**Comment by bhashemi** [comment]
@Hadrien-Montanelli , I have looked at this branch and the only question I have is the following: In the last commit, 'etdrk4' is replaced with 'etdrk2' when a multistep scheme is started. I am curious to know the reason for this. 

Otherwise I am happy to merge this pull-request once  #1982 is merged and I could run all the tests. By the way, your coding style is great!

**Comment by Hadrien-Montanelli** [comment]
Thanks @bhashemi - see pull request #1982 for 'etdrk2' vs 'etdrk4'

**Comment by Hadrien-Montanelli** [comment]
@bhashemi I still have to update the documentation in some files; hold the merge for now.

**Comment by bhashemi** [comment]
@Hadrien-Montanelli , let me know if you are done.

**Comment by Hadrien-Montanelli** [comment]
I think it's ok! 

-----------------------------------------------------------------------
Hadrien Montanelli
University of Oxford, Balliol College
PhD student in Mathematics
Address: Mathematical Institute, Oxford OX2 6GG
Web: www.maths.ox.ac.uk/people/hadrien.montanelli

----- Original Message -----

**Pull request merged**
