### PR TITLE
Fast(est) spherefun rotation

### PR DESCRIPTION
**Pull request by ajt60gaibb**
This PR puts in the 2D NUFFT to allow for faster rotation. There have been three algorithms in `spherefun.rotate` since the start of spherefun: 
 - "Call the constructor":  Terribly slow first attempt. Never used now. 
 - "FEVAL": Evaluate the rotated spherefun at carefully selected points using Horner's algorithm. Recommended when `min(m,n) <= 150`, where `[m,n] = length(f)`. 
- "NUFFT": Evaluate the rotated spherefun at carefully selected points using the 2D NUFFT algorithm. Recommended when `min(m,n) > 150`, where `[m,n] = length(f)`. 

We need both "FEVAL" and "NUFFT". When `min(m,n) > 150`, NUFFT gives a speed up and allows us to do larger problems efficiently.  For example,
```
f = randnfunsphere( 0.03 );
[m,n] = length(f)
m =
   211
n =
   213
```
The execution times for FEVAL and NUFFT are (after significant speed up based on comments below from @gradywright):
```
tic, g = rotate(f, 0.1, 0.1, 0.1,'feval'); toc
Elapsed time is 21.296767 seconds.
tic, g = rotate(f, 0.1, 0.1, 0.1,'nufft'); toc
Elapsed time is 1.996383 seconds.
```
I did a more detailed comparison to get the `150` changeover: 

```
omega = 1:2:100;
ii = 1; 
for w = omega
    f = spherefun( @(x,y,z) cos(w*x.*y)+z );
    [m(ii), n(ii)] = length(f);
    s = tic; 
    g1 = rotate(f, 0.1, 0.1, 0.1, 'feval');
    t_feval(ii) = toc(s);
    s = tic; 
    g2 = rotate(f, 0.1, 0.1, 0.1, 'nufft');
    norm(g1 - g2)
    t_nufft(ii) = toc(s);
    ii = ii + 1;
end
```
rotatecomparison2

### CODE REVIEW

**Comment by ajt60gaibb** [comment]
Ironically, performing FFTs in the `spherefun.FastSphereEval` is less than 1% of the cost. This makes me feel that we are a few MATLAB tricks away from a *much* faster `spherefun.FastSphereEval` code.

**Comment by ajt60gaibb** [comment]
@gradywright, one should be able to make line 106 of `spherefun.FastSphereEval` *much* faster and speed up the NUFFT-based rotate by x4 (judging from profile on).  Notice that I loop over `ii`, but most of the `ii`s are the same so I'm repeating those matrix-matrix mults with the same quantities.

**Comment by nickhale** [comment]
You can shave off another epsilon by using cells rather than multidimensional arrays in a couple of places..

```
[c, ~, ic2] = unique([ii jj], 'rows');
temp = cell(size(c,1),1);
for idx = 1:size(c,1)
    temp{idx} = YY(:,:,c(idx,1))*XX(:,:,c(idx,2));
end
Aij = cell(numel(ii),1);
for idx = 1:numel(ii)
    Aij{idx} = temp{ic2(idx)};
end
Aij = cat(3, Aij{:});
```

**Comment by nickhale** [comment]
Best I can do (about 1 sec faster than @gradywright 's code for the given example):

```
% Convert to cell for speed:
XXX = cell(size(XX,3),1);
for k = 1:length(XXX)
    XXX{k} = XX(:,:,k);
end
YYY = cell(size(YY,3),1);
for k = 1:length(YYY)
    YYY{k} = YY(:,:,k);
end
% Do only unique multiplications:
[c, ~, ic2] = unique([ii jj], 'rows');
temp = cell(size(c,1),1);
for idx = 1:size(c,1)
    temp{idx} = YYY{c(idx,1)}*XXX{c(idx,2)};
end
% Recover A:
Aij = cell(numel(ii),1);
for idx = 1:numel(ii)
    Aij{idx} = temp{ic2(idx)};
end
Aij = cat(3, Aij{:});
```

**Comment by gradywright** [comment]
Thanks @nickhale!  Your matlab skills never cease to amaze me.

**Comment by gradywright** [comment]
With @nickhale's optimizations and some more of my own, the `nufft` code is now faster, and the changeover point has pretty much disappeared on @ajt60gaibb's test problem.
rotatecomparison3

**Comment by ajt60gaibb** [comment]
I'm busy for one afternoon, and I miss this. Wow!  Amazing stuff, very very cool.

**Comment by ajt60gaibb** [comment]
@nickhale, do you know how to speed up line 131? 
```
SA = sum(Aij.*repmat(U2,[K1, 1, 1]), 2);
```
Seems redundant to have to `repmat` and for very low rank spherefuns this is the significant cost of the algorithm!

**Comment by gradywright** [comment]
@ajt60gaibb I removed that computation quite a few commits ago.  Everything is now rolled into one for loop to compute the values.

**Comment by nickhale** [comment]
I am happy for this to be merged, but perhaps @gradywright should also take a look (particularly at my final set of changes)

**Comment by gradywright** [comment]
Thanks for tidying up the code @nickhale.  I just added more extensive tests for rotate.  I believe it is now ready to merge.

**Comment by ajt60gaibb** [comment]
Sorry I wasn't able to contribute much yesterday.  I was traveling.  Thanks for making the code faster. Looks sweet. 

For comparison (15x speed up): 
```
f = randnfunsphere(0.03);
tic, g = rotate(f,0.1,0.1,0.1);toc
Elapsed time is 1.462974 seconds.
```

**Pull request merged**
