### PR TITLE
Fix jacpts

### PR DESCRIPTION
**Pull request by LourencoPeixoto**
Compute the constant out the front in a more stable way using the ratio of gamma functions. See #1707.

### CODE REVIEW

**Comment by aaustin141** [comment]
This change is simple enough that I'm tempted to merge it, but after reading through the discussion on #1707, I'm not left with the sense that we've not quite reached consensus on what to do here yet.  This implements the "ratio of gamma functions" approach to computing this constant, but as you point out in [your comment](https://github.com/chebfun/chebfun/issues/1707#issuecomment-172024658) on that thread, this can be problematic for small n, and this pull request doesn't do anything about that.

Also, there should probably be a test or two added to `tests/misc/test_jacpts.m` to check for this issue since it's so subtle.  (#1702 should have done this as well but didn't.)

**Comment by nickhale** [comment]
For small `n` the direct calculation of this constant (via `gamma()`) should cause no trouble.

**Comment by LourencoPeixoto** [comment]
I've updated the file as we point out in #1707. Now is fine to me.

Also, I'm going add some tests to ```tests/misc/test_jacpts.m```.

**Comment by nickhale** [comment]
I think you need the conditional to be on the size of `n`, not on the method used?

**Comment by LourencoPeixoto** [comment]
Oh, indeed! I'll fix now!

**Comment by LourencoPeixoto** [comment]
I think that there are some typing errors on comments. Also, I believe that 

```w(end) = .5*w(end);```

 is missing on the line 897. See 08f7873.

**Comment by aaustin141** [comment]
@LourencoPeixoto:  This is looking better; thanks for your work!  Can you add one more test that checks the validity of the change you proposed to the line you mentioned?

**Comment by LourencoPeixoto** [comment]
@aaustin141: Actually the code

`w(end) = .5*w(end);`

on the line 897 that I proposed is not affecting the `jacpts` commmand now because the function `asy2_higherterms` is not calling that. I proposed this change just in case. Therefore the test doesn't make sense unless we increase the number of output arguments in `asy2_higherterms`... Recall that only four output arguments are necessary and sufficient, namely `tB1`, `A2`, `tB2` and `A3`. I believe that @nickhale or @ajt60gaibb could say if this change is really fine.

On the other hand, we also could delete all the lines that not are being called:

```
% A3p:
A3p = D*A3;
A3p = A3p - A3p(1);
A3p_t = A3p./t;
% Extrapolate point at t = 0:
w = pi/2-t(2:end);
w(2:2:end) = -w(2:2:end);
w(end) = .5*w(end);
A3p_t(1) = sum(w.*A3p_t(2:end))/sum(w);

% B3:
tB3 = -.5*A3p - (.5+alph)*(C*A3p_t) + .5*C*(f.*A3);
B3 = tB3./t;
% Extrapolate point at t = 0
B3(1) = sum(w.*B3(2:end))/sum(w);

% A4:
K = C*(f.*tB3);
A4 = .5*(D*tB3) - (.5+alph)*B3 - .5*K;
A4 = A4 - A4(1);

% Make function for output:
tB1 = @(theta) bary(theta, tB1, t, v);
A2 = @(theta) bary(theta, A2, t, v);
tB2 = @(theta) bary(theta, tB2, t, v);
A3 = @(theta) bary(theta, A3, t, v);
tB3 = @(theta) bary(theta, tB3, t, v);
A4 = @(theta) bary(theta, A4, t, v);
```

 @nickhale, @ajt60gaibb: any suggestion?

**Comment by nickhale** [comment]
As far as @LourencoPeixoto is correct, and it should be `w(end) = .5*w(end);`. (Of course, what we should have done was to use 1st-kind points, in which case this extrapolation would not have been necessary!)

However, I also agree that for clarity we may as well remove the code which is never called.

**Comment by LourencoPeixoto** [comment]
Ok, @nickhale. I have removed the code which is never called. See 319dde9.

**Comment by aaustin141** [comment]
All right---this is looking good to me now.  @nickhale:  do you have any further comments on this, or am I OK to merge it?

**Comment by nickhale** [comment]
This looks OK.

There's still a *lot* of duplication between `legpts()`, jacpts()`, and `ultrapts()` (as pointed out in #1645), but that's for another day.

**Comment by LourencoPeixoto** [comment]
Regarding duplication, are #1650 and #1651 not sufficient for now?

Of course, with the updated `ultrapts()` in #1725, we have new overlaps that could be arranged.

**Pull request merged**
