### PR TITLE
Add poisson operator

### PR DESCRIPTION
**Pull request by ajt60gaibb**

### CODE REVIEW

**Comment by nickhale** [comment]
Can I propose (a) naming this method `laplace` rather than `setuplaplace` and (b) taking the default domain from `cheboppref` if none is passed? 

Might it be useful to add other operators (e.g., Helmholtz)?

**Comment by ajt60gaibb** [comment]
I did `setuplaplace->laplace`.  Did you really mean `cheboppref` (the preferences for the 1D code)? We don't have a `chebop2pref` but we could pull from that preference structure if we make one...

**Comment by nickhale** [comment]
`chebop2` gets a default domain from somewhere:
```
>> chebop2(@(u) lap(u))
chebop2 of rank 2: (linear bivariate operator)
         domain               operator  
[ -1,  1] x [ -1,  1]  @(u)lap(u)
```

**Comment by ajt60gaibb** [comment]
hardcoded. gulp.

**Pull request merged**
