### PR TITLE
Fix chebop display

### LINKED ISSUE #1293: What does "u-BC" mean in a boundary condition?
I notice that the command
```
>> L = chebop(@(x,u) diff(u) + diff(u,2), [-1, 1], 0, @(u) diff(u))
```
produces the result
```
L =
   Linear operator:
      diff(u)+diff(u,2) = 0
   operating on chebfun objects defined on:
      [-1 1]
   with
    left boundary conditions:
      u-BC = 0
    right boundary conditions:
      diff(u) = 0
```
I don't understand what "u-BC" means, and I can imagine that users won't understand either.  If this is a bug, could it be fixed?  If it's not a bug, could it be explained to me?  Thanks.

### PR DESCRIPTION
**Pull request by asgeirbirkis**
Closes #1293 and #1443. Some example outputs for displaying ```chebops```:

```
>> N = chebop(@(u) diff(u,2)); N.lbc = 'neumann'; N.rbc = 2
N =
   Linear operator:
      u |-> diff(u,2)
   operating on chebfun objects defined on:
      [-1 1]
   with
    left boundary condition(s):
      neumann
    right boundary condition(s):
      u = 2
```

```
>> N = chebop(@(u) diff(u,2)); N.bc = 'dirichlet'
N =
   Linear operator:
      u |-> diff(u,2)
   operating on chebfun objects defined on:
      [-1 1]
   with
    left boundary condition(s):
      dirichlet
    right boundary condition(s):
      dirichlet
```

```
>> N = chebop(@(x, u, v) [diff(u) - v.^2 ; u - diff(v)], [0 3]); N.lbc = @(u,v) u-2; ...
N.rbc = @(u,v) diff(v) + u
N =
   Nonlinear operator:
      u,v |-> diff(u)-v.^2
              u-diff(v)
   operating on chebfun objects defined on:
      [0 3]
   with
    left boundary condition(s):
      u-2 = 0
    right boundary condition(s):
      diff(v)+u = 0
```

### CODE REVIEW

**Comment by asgeirbirkis** [comment]
With ff6e1a7, we now print commas in the domains for `chebop` display (in accordance with a survey carried out by @trefethen outside the Andrew Wiles building). We now get:
```
>> format compact
>> L = chebop(@(u) diff(u),[-1 6])
L =
   Linear operator:
      u |-> diff(u)
   operating on chebfun objects defined on:
      [-1,6]
```
I.e. no space when the endpoints are integers. When they're non-integers, the whitespace is retained:
```
>> L = chebop(@(u) diff(u),[-1 pi 6])
L =
   Linear operator:
      u |-> diff(u)
   operating on chebfun objects defined on:
      [-1, 3.14159, 6]
```

**Comment by mhsnjvd** [comment]
Purely cosmetic comment, I think 
```
u |-->
```
looks better than 
```
u |->
```
@asgeirbirkis ?

**Comment by asgeirbirkis** [comment]
I'm happy with either, whatever the team prefers!

**Comment by asgeirbirkis** [comment]
ed256cc replaces `|->` with `|-->`, as was discussed at last meeting. The output of the examples above now looks as follows:
```
>> N = chebop(@(u) diff(u,2)); N.lbc = 'neumann'; N.rbc = 2
N =
   Linear operator:
      u |--> diff(u,2)
   operating on chebfun objects defined on:
      [-1,1]
   with
    left boundary condition(s):
      neumann
    right boundary condition(s):
      u = 2


>> N = chebop(@(u) diff(u,2)); N.bc = 'dirichlet'
N =
   Linear operator:
      u |--> diff(u,2)
   operating on chebfun objects defined on:
      [-1,1]
   with
    left boundary condition(s):
      dirichlet
    right boundary condition(s):
      dirichlet

>> N = chebop(@(x, u, v) [diff(u) - v.^2 ; u - diff(v)], [0 3]); N.lbc = @(u,v) u-2; ...
N.rbc = @(u,v) diff(v) + u
N =
   Nonlinear operator:
      u,v |--> diff(u)-v.^2
               u-diff(v)
   operating on chebfun objects defined on:
      [0,3]
   with
    left boundary condition(s):
      u-2 = 0
    right boundary condition(s):
      diff(v)+u = 0
```

**Pull request merged**
