### PR TITLE
Add pde23t() method which is better than pde15s() for advection-dominated problems.

### PR DESCRIPTION
**Pull request by nickhale**
We know that `pde15s()` does pretty well for diffusive problem, but can struggle otherwise. The archetypal example is Maxwell's equation (see #405.)

While experimenting with a coefficient-based version of `pde15s()` I noticed that a lot of noise was being placed in to the highest-order Chebyshev coefficients by `ode15s()` during the time-stepping phase. On a whim I decided to try one of the other MATLAB solvers, `ode23t()`. (This might seem a strange choice, but because of the way we enforce boundary conditions we require the ability to solve with singular Mass matrices, and `ode23t()` and `ode15s()` are the only built in solvers which can do this.)

It turned out this was a *lot* faster on the Maxwell's example than `pde15s()`, even for the existing values-based approach. I decided to create a `pde23t()` method so that this can be explored further. Below is the comparison I made:

```
pdefun = @(t, x, E, B) [ diff(B), diff(E) ];
bc.left = @(t, x, E, B) E;
bc.right = bc.left;
d = [-2, 2];
x = chebfun('x', d);
E0 = exp(-16*x.^2);
t = 0:0.05:1;
opts = pdeset('plot', 'off');
```
```
>> tic, soln = pde15s(pdefun, t, [E0, -E0], bc, opts); toc
Elapsed time is 11.051078 seconds.
```

```
>> tic, soln2 = pde23t(pdefun, t, [E0, -E0], bc, opts); toc
Elapsed time is 1.327562 seconds.
```

Plotting the Chebyshev coefficients gives an indication as to why `pde15s()` is so much slower:

```
plotcoeffs(soln)
```
coeffs1

```
plotcoeffs(soln2)
```
coeffs2

### CODE REVIEW

**Comment by asgeirbirkis** [comment]
@nickhale should we make this an option in Chebgui as well, i.e., allow users to select between pde15s and pde23t for their problems?

**Comment by nickhale** [comment]
Sure, that sounds sensible.

**Comment by asgeirbirkis** [comment]
OK, I'm happy to write the functionality for the GUI option.

However, I'm looking at the pull request now, and I have an issue with `pde23t` simply calling `pde15s` with a different option. Surely, there should be a method at top, e.g. `solvePDE`, that both methods should call with different options?

Along those lines, maybe we should use this opportunity to refactor the `pde15s` method? As we all know, it's a beast of an m-file, as I recently got reminded of while working on #1476. It'd make a lot of sense to me to pull out most of the subfunctions and put in separate files, perhaps via introducing a new helper class?

On a more ambitious and interesting note, how realistic would it be to try to diagnose PDEs before calling the solvers, and choose pde15s or pde23t according to whether the problem is diffusive or not?

**Comment by nickhale** [comment]
Thanks.

I thought about completely refactoring things, but I decided that perhaps before expending too much effort on that it would be best to get some idea of how useful the new functionality would be and whether a more extensive rewrite would be worthwhile. (In principle there's no reason to to allow user defined ode solvers, as long as they have the required functionality (i.e., allowing singular mass matrices)).

Again, I'm not sure if refactoring `pde15s()` in its current state is worthwhile. In particular, if a lot of effort was being expended on this, I would almost certainly advocate moving to a coefficient-based approach rather than values-based (see #1191). At one point my understanding was that `pde15s()` was going to be made obsolete by spectral deferred correction, but I haven't heard anything from that direction in a long time.

MATLAB makes no attempts to diagnose ODEs, it just gives you the plethora of `ode***()` routines and tells you which is best in certain situations. I don't think we need to try and automate the process for ODEs.

**Comment by asgeirbirkis** [comment]
OK, maybe we should hold on with the complete refactoring, but as a compromise in the meantime, I think it'd be worth introducing the `pdeSolve` method that both `pde15s` and `pde23t` would call -- I found this confusing when I first looked at it, and that's even after having spent decent amount of time in the PDE district of Chebfunland, so anyone else looking at this will probably find it confusing as well. I think all it'd require is essentially to rename the current `pde15s` to the new method, and then make `pd15s` look similar to the new `pde23t`.

**Comment by nickhale** [comment]
One possible reason for the difference in performance between the two solvers (although I stress that I have essentially no evidence to back this up) is that `ode15s()` introduces high frequency noise at each time step whereas `ode23t()` introduces low frequency noise. 

The former is much worse in this setting, both because the higher-degree Chebyshev coefficients then grow rapidly as we take further derivatives and because it causes 'unhappiness' and forces the `length` of the chebfun to grow.

**Pull request merged**
