### PR TITLE
Fix-trigcolloc-fredvolt

### PR DESCRIPTION
**Pull request by nickhale**
Support for Fredholm operators in `trigcolloc` discretisation.

Volterra operators are complicated for the same reason that the `cumsum` (indefinite integral operator) is complicated for trig-discretisations, i.e., that unless you enforce something like a zero-mean condition, then the indefinite integral of a `trigtech` is not necessarily a `trigtrech`.

### CODE REVIEW

**Comment by Hadrien-Montanelli** [comment]
@nickhale - could you please add a test?

**Comment by Hadrien-Montanelli** [comment]
(Otherwise happy to merge it.)

**Comment by Hadrien-Montanelli** [comment]
Any update @nickhale?

**Comment by nickhale** [comment]
Done.

**Comment by Hadrien-Montanelli** [comment]
Thanks @nickhale.

**Pull request merged**
