### PR TITLE
Fix chebfun2 simplify tol

### PR DESCRIPTION
**Pull request by jaurentz**
This pull request addresses the problem in #1776. The key problem, as pointed out by @bhashemi, is that the `tol` computed during phase 1 of the `chebfun2` constructor is not being passed on to the `simplify` call at the end of phase 2. This can result in a tighter simplification tolerance than what was ultimately used for construction.

### CODE REVIEW

**Comment by aaustin141** [comment]
This change looks innocuous enough, but the last commit highlights a few things that I don't understand.  Is the tolerance `tol` supposed to be absolute or relative?  That is, is it supposed to incorporate the `vscale` or not?

One would think this question would be answered by [this line](https://github.com/chebfun/chebfun/blob/29b2386e1018928b32ae315b4f3cb16a93692c2d/%40chebfun2/constructor.m#L526) in `getTol()`, which clearly builds the `vscale` into `tol`.  That also seems to be consistent with its usage in, say, the `completeACA()` subfunction and in `separableApprox.sampleTest()`.  But then, I see things like [this line](https://github.com/chebfun/chebfun/blob/29b2386e1018928b32ae315b4f3cb16a93692c2d/%40chebfun2/constructor.m#L97) in which it's being used as if that's not supposed to be the case.  I also see `tol` being inserted into `pref.eps` in [this line](https://github.com/chebfun/chebfun/blob/29b2386e1018928b32ae315b4f3cb16a93692c2d/%40chebfun2/constructor.m#L130), but `pref.eps` is supposed to be a relative tolerance, not an absolute one.

What's going on here?  Are these latter lines just wrong?  @ajt60gaibb, can you comment on this?

**Comment by ajt60gaibb** [comment]
@aaustin141, I have not been keeping up with the chopping/simplify changes.   I think @bhashemi and @jaurentz know far more about the tolerances in the chebfun2 constructor than I do at this point.

**Comment by aaustin141** [comment]
Very well, then.  @bhashemi, do you have any comments to make about the role of `tol` here and, in particular, whether it is supposed to relative or absolute?

**Comment by jaurentz** [comment]
I've updated the subroutine `getTol` to output both a vscale and hscale-invariant `relTol` and the original output which is now called `absTol`. There are no fancy tricks here, just a refactoring of the variables for clarity. Now whenever `getTol` is called the internal `pref.eps` is set to equal `relTol`. This means that both `happinessCheck` and `simplify` use `relTol` and the rest of the code uses `absTol` as it did before.

**Comment by bhashemi** [comment]
@aaustin141 , considering these last changes, is this now clear enough?

**Comment by bhashemi** [comment]
I think this PR needs more work before being merged, as #1776 still persists!

**Comment by jaurentz** [comment]
Added the magic `grid^(2/3)` factor to the computed `relTol`. This fixes the problem in #1776.

**Pull request merged**
