### PR TITLE
feature-ultrapts

### PR DESCRIPTION
**Pull request by LourencoPeixoto**
Ultraspherical points and Gauss-Gegenbauer quadrature weights. The ultrapts() command is analogue of 
chebpts(), legpts(), jacpts(), and hermpts(). This code is much faster than the more general jacpts() command when alpha=beta.

### CODE REVIEW

**Comment by aaustin141** [comment]
@LourencoPeixoto:  Sorry to be slow to start looking at your code.  This looks pretty nice so far!

One thing I notice is that there aren't yet any tests for your code.  Could you add a test script `tests/misc/test_ultrapts.m` with some tests in it?  You might start by taking a look at the test scripts for `jacpts` (`tests/misc/test_jacpts.m`) and `legpts` (`tests/misc/test_legpts.m`) and patterning yours after those.

**Comment by LourencoPeixoto** [comment]
Hi @aaustin141!

Yes, I will add this test script!

**Comment by LourencoPeixoto** [comment]
Hi @aaustin141! 

I've added the test script `tests/misc/test_ultrapts.m` #1629.

**Comment by aaustin141** [comment]
Great!  Glad to see that you've done this!

Instead of handling this through a separate pull request, it would be better to incorporate it into this one.  Can you push your test script to your patch-1 branch?

**Comment by ajt60gaibb** [comment]
@LourencoPeixoto, the outputs vectors are not consistent with `jacpts`. (Easy fix.) For example: 
```
[x, w] = jacpts( 1000, .4, .4 );
size(w)
ans =
           1        1000
[x, w] = ultrapts( 1000, .9 );
size(w)
ans =
        1000           1
```

Otherwise, this looks great to me!

**Comment by LourencoPeixoto** [comment]
Hi @ajt60gaibb,

I've fixed!

**Comment by LourencoPeixoto** [comment]
Hi @aaustin141, I've already pushed the test script to the patch-1 branch.

**Comment by aaustin141** [comment]
@LourencoPeixoto:  Again, my apologies for being slow.  Everything looks fine to me now.  Just one more thing:  could you take a look at the new [CONTRIBUTING.md](https://github.com/chebfun/chebfun/blob/development/CONTRIBUTING.md) file and write back here to indicate that you're OK with the statement contained therein regarding licensing?  Once you've done this, we should be good to go!

**Comment by LourencoPeixoto** [comment]
@aaustin141, I read the CONTRIBUTING file. I agree with all the statements contained therein regarding licensing. It's everything OK to me!

**Comment by aaustin141** [comment]
All right, we're done.  Thank you for your patience!

**Comment by LourencoPeixoto** [comment]
Thank you, @aaustin141 ! I'm glad to see this!

**Pull request merged**
