### PR TITLE
feature-chebtech-lvalrval

### LINKED ISSUE #1171: Avoid using FEVAL() in @CHEBTECH/GET(f, 'RVAL').
It would be more efficient to simply sum the Chebyshev coefficients.

One could do something similar for `@chebtech/get(f, 'lval')`.

(Looking at profile reports from @hrothgar's v4-v5 comparisons (see #1130), often a lot of time was spent in `clenshaw_scl.m`. The fix suggested above might fix a lot of this.)

### PR DESCRIPTION
**Pull request by nickhale**
Add chebtech/lval() and chebtech/rval(). 

Closes #1171.

### CODE REVIEW

**Comment by asgeirbirkis** [comment]
Looking at #1130, which inspired #1171 which in turn this pull request is aimed at, it would be nice if we had an automated way of comparing running times between different commits. Essentially something that would automatically generate the table that @hrothgar posted on #1130, and compare between runs. Thoughts @hrothgar or @aaustin141 ?

**Comment by hrothgar** [comment]
It wouldn't be too hard to put together a script to do that, although it is slightly complicated by the necessary switching between branches, both because that (probably) has to be done manually and because all the variables need to be cleared when doing so.

Has anyone thought of adding V4 as a branch on this repo to make it easier to switch back and forth? Might be a good idea, too.

**Comment by asgeirbirkis** [comment]
I think adding v4 to the repo is a good idea, not least for ensuring that the code doesn't get lost (not that it's a high risk event, but it'd be nice to have all chebfun code available at one place).

I think that the script doesn't have to be too complicated, and I'd be happy with the following scenario, at least for a start:

1. Run the timing script, output a log file with the times each method took.
2. Switch branches manually, clear all variables manually
3. Run the timing script again, but this time, with the output from (1) as an input
4. Output a log file with the comparision table from @hrothgar's comment in #1130 on 18/09.

To begin with, I don't think it's necessary to include v4 in the comparison, comparing between different versions of v5 would be fine. Essentially, a mechanism for checking whether changes we're doing to the development branch are speeding up or slowing down the code.

**Comment by asgeirbirkis** [comment]
(Sorry @nickhale for hijacking this thread)

**Comment by nickhale** [comment]
No problem - I think it's a good idea. 

I don't expect this particular pull request to have a massive effect, however.

**Comment by hrothgar** [comment]
@nickhale, I've taken the liberty of putting your function `compare_branches` on Gist to keep track of it.

https://gist.github.com/hrothgar/51b10c867d3dcef0c026

**Comment by asgeirbirkis** [comment]
I like this script, maybe we could discuss it on the meeting next week and if everyone is happy, get it into development?

**Pull request merged**
