### PR TITLE
Fix chebfun2 constructor fixed rank, fixed length, and domain input parsing

### LINKED ISSUE #1824: Chebfun2 fixed rank construction not working for chebfun2 inputs
Consider the following:
```
>> f = chebfun2(@(x,y) exp(cos(x.*y)))
 
f =
 
   chebfun2 object
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        9     [ 1.7  1.7  1.7  1.7]
vertical scale = 2.7 
```
Now lets construct a chebfun2 object from `f` with a fixed rank of 2:
```
>> g = chebfun2(f,2)
 
g =
 
   chebfun2 object
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        9     [ 1.7  1.7  1.7  1.7]
vertical scale = 2.7 
```
The Chebfun2 constructor appears to just return `f` back without truncating its rank.

### PR DESCRIPTION
**Pull request by gradywright**
Fixes #1824 and the other problems raised by @ajt60gaibb under this issue.  Closes #1824.

### CODE REVIEW

**Comment by ajt60gaibb** [comment]
That's great. Thank you. 👍

**Comment by ajt60gaibb** [comment]
@gradywright, I still get this: 

```
g = chebfun2( @(x,y) sin(x.*y), [10 15], [-2 1 -2 1]);

Error using chebfun2/constructor>parseInputs (line 569)
Domain not valid or fully determined.
Error in chebfun2/constructor (line 31)
[op, dom, pref, isEqui, fixedRank, vectorize] = parseInputs(op,
varargin{:});
Error in chebfun2 (line 57)
            f = constructor(f, varargin{:}); 
```

**Comment by gradywright** [comment]
Thanks @ajt60gaibb for catching this.  It should be fixed now.

**Comment by ajt60gaibb** [comment]
Thanks.

**Pull request merged**
