### PR TITLE
Fix chebgui cheboppref

### PR DESCRIPTION
**Pull request by asgeirbirkis**
Various changes to chebgui to address changes introduced in #1550 .

### CODE REVIEW

**Comment by Hadrien-Montanelli** [comment]
@asgeirbirkis the "Advection-Diffusion with periodic BCs" example works with values but fails with coefficients.

**Comment by asgeirbirkis** [comment]
@Hadrien-Montanelli that's because it's waiting for me to merge #1496 :) It tries using `trigspec`, which I'll hopefully get merged tomorrow, or at least before the end of this week.

**Comment by Hadrien-Montanelli** [comment]
Indeed! Sorry about the confusion!

**Comment by asgeirbirkis** [comment]
As a reminder, as a part of merging this, the warnstate offs in `chebgui/solveGUI` and `tests/chebgui/solvegui_eig` should be removed.

**Comment by nickhale** [comment]
As #1496 has been merged, is this ready for review now?

**Comment by Hadrien-Montanelli** [comment]
I'm on it!

**Pull request merged**
