### PR TITLE
Only allow happy funs to contribute to global vscale in piecewise construction.

### LINKED ISSUE #1486: bug: failure of `chebfun(tan(x))`
Something very basic is going wrong here!
```
>> f = chebfun(@(x) tan(x),[0 pi],'splitting','on','blowup','on')
f =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[       0,     3.1]        1       -64      -64 
epslevel = 2.848295e-01   vscale = 6.365674e+01
```

### PR DESCRIPTION
**Pull request by nickhale**
Closes #1486.

```
>> f = chebfun(@(x) tan(x),[0 pi],'splitting','on','blowup','on')
f =
   chebfun column (2 smooth pieces)
       interval       length     endpoint values   endpoint exponents
[       0,     1.6]       21   2.1e-16      Inf         [0      -1]  
[     1.6,     3.1]       23      -Inf -1.5e-15         [-1      0]  
epslevel = 1.000000e-14   vscale = 16331239353195370   Total length = 44
```

NB: One can argue whether `vscale = 16331239353195370` is useful/correct.
(Is it useful/correct if `vscale = inf`?)

### CODE REVIEW

**Comment by asgeirbirkis** [comment]
@mhsnjvd at the moment, you're assigned to this ticket. Are you looking into this, it would be nice to get it merged before the v5.2 release? Let me know if you prefer it to be assigned to someone else!

**Comment by mhsnjvd** [comment]
@asgeirbirkis  @nickhale  There are vscales involved. Actually, vscales was the reason for this bug. I thought it would be better to have #1500 merged first.

**Comment by nickhale** [comment]
Although `vscales` are involved in both, the two are independent. This branch deals with `vscales` that are carried around in the construction process. The other deals with the `vscales` stored in `chebtech` objects. (It's likely that the two will even merge cleanly.)

**Comment by mhsnjvd** [comment]
I am happy to merge it in that case - I have looked at the code. However, we do have a conflict in  tests/chebfun/test_restrict.m it's a tolerance issue.  @nickhale if you can "fix" that, I will go ahead with the merge.

**Comment by nickhale** [comment]
Thanks @mhsnjvd. It should be "fixed".

**Pull request merged**
