### PR TITLE
Hotfix rename expint

### LINKED ISSUE #2223: Chebfun replaces built-in function EXPINT and breaks existing code
Chebfun replaces MATLAB's built-in function [EXPINT](https://www.mathworks.com/help/matlab/ref/expint.html) with its own class with the same name, but different semantic.

This breaks programs which uses the built-in [EXPINT](https://www.mathworks.com/help/matlab/ref/expint.html) function. After installing the Chebfun: 

```
>> expint(rand(100))
Error using expint (line 251)
Unrecognized scheme. 

>> which expint
[...]\chebfun\@expint\expint.m  % expint constructor
```

This is quite serious issue, as it breaks default and expected MATLAB behavior.
Would appreciate if you consider fixing it (e.g. by switching to non-intrusive name for your class).

### PR DESCRIPTION
**Pull request by Hadrien-Montanelli**
Fixes #2223.

### CODE REVIEW

**Comment by Hadrien-Montanelli** [comment]
@sfilip @nakatsukasayuji Could you guys have a quick look at this? It just changes Chebfun's `expint` to `expinteg` to avoid a clash with MATLAB's `expint` function. The merge would have to go to the master's branch directly.

**Comment by sfilip** [comment]
I'll have a look this afternoon.

**Comment by Hadrien-Montanelli** [comment]
Thanks @sfilip!

**Comment by Hadrien-Montanelli** [comment]
After discussions with @sfilip, we'll just merge this to development.

**Comment by sfilip** [comment]
The changes look good to me. I'm happy to merge. Thanks @Hadrien-Montanelli!

**Pull request merged**
