### PR TITLE
fix-delta-quasi-plot-colors

### LINKED ISSUE #1316: Plotting a quasimatrix with columns that have delta functions crashes.
It seems we can't plot quasimatrices that have columns with delta functions:
```
>> x = chebfun(@(x) x);
>> Q = [dirac(x) dirac(x)];
>> plot(Q)
Error using stem (line 41)
Too many input arguments.
Error in chebfun/plot>mystem (line 446)
    h(j) = stem(data{:}, 'fill');
Error in chebfun/plot (line 358)
    h4 = mystem(deltaData{:}); 
```

### PR DESCRIPTION
**Pull request by aaustin141**
This closes #1316.

@mhsnjvd, would you be willing to take a look at this and let me know what you think?

### CODE REVIEW

**Comment by mhsnjvd** [comment]
@aaustin141  Now the more basic example fails:

```
x = chebfun('x');
d = dirac(x);
plot(d, 'r');
```

**Comment by aaustin141** [comment]
Are you sure?  It's working just fine for me, at least on R2014b...

**Comment by asgeirbirkis** [comment]
Breaks for me on 2013a, Linux, as well as 2014b, Mac:
```
>> git status
On branch fix-delta-quasi-plot-colors
Your branch is up-to-date with 'upstream/fix-delta-quasi-plot-colors'.
>> >> x = chebfun('x');
d = dirac(x);
plot(d, 'r');
Error using plot
Conversion to double from cell is not possible.
Error in chebfun/plot>plotDeltasForOneFunction (line 511)
    h(j) = plot(fullData{:});
Error in chebfun/plot>plotDeltas (line 438)
        h = [h, plotDeltasForOneFunction(deltaData{k}{:})]
Error in chebfun/plot (line 355)
    h4 = plotDeltas(deltaData); 
```

**Comment by aaustin141** [comment]
OK.  This should be fixed now.  Sorry about that; I was being a bozo.

**Pull request merged**
