### PR TITLE
Implement BIHARMONIC operator for CHEBFUN2.

### PR DESCRIPTION
**Pull request by Hadrien-Montanelli**

### CODE REVIEW

**Comment by Hadrien-Montanelli** [comment]
@ajt60gaibb, can I assign this to you?

**Comment by ajt60gaibb** [comment]
@Hadrien-Montanelli, I prefer not to merge code into development these days.  

The code looks good.  You should add a test.

**Comment by bhashemi** [comment]
@Hadrien-Montanelli , please assign this to me, if you think I can.

**Comment by Hadrien-Montanelli** [comment]
Thanks for your answers @ajt60gaibb and @bhashemi.

**Comment by bhashemi** [comment]
@Hadrien-Montanelli , I added a test to this branch. All the tests pass on my machine. So, if you are happy with ``chebfun2/test_biharm``, I'll merge this PR.

**Comment by Hadrien-Montanelli** [comment]
Looks good @bhashemi

**Comment by Hadrien-Montanelli** [comment]
Thanks!

**Pull request merged**
